### ISSUE TITLE
Ajouter des options de layout

### ISSUE THREAD

**Issue by zhouzi** [zhouzi/broll#17]
Ajouter la possibilité de basculer entre un layout vertical (actuel) et un layout horizontal, un peu comme celui-ci :

![](https://github.com/zhouzi/broll/assets/2291025/d99ca65f-4b21-4510-9a34-c168c41b9060)

Mais pas toutes ces informations bien sûr, uniquement celles qu'on propose déjà.

En terme d'implémentation je me demande si il ne vaudrait pas mieux avoir 2 composants, plutôt que simplement changer des règles CSS. Parce qu'en terme de structure, il y a des différences significatives, comme le placement du logo de la chaîne et le nom.

Ça permettrait une plus grande flexibilité et du code plus simple. En sachant qu'on peut partager les composants entre les implémentations. Mais je préfère dupliquer un peu de code bête que d'avoir qu'un seul gros bloc compliqué.

**Comment by mootookoi** [comment]
Je bosse dessus là.
Si on fait deux modules différents, il faut qu'on passe la props du layout jusqu'à renderPNG().
On part comme ça ?

**Comment by zhouzi** [comment]
En fait le layout ne devrait pas être séparé du thème mais faire partie de la liste d'options, à ajouter par là : 

![](https://github.com/zhouzi/broll/assets/2291025/d13a445d-e6bc-4a83-aa19-ec43bf9a84b5)

Dans l'idée le thème englobe tous les paramètres qui influe sur l'apparence du rendu. Et si le layout y est ajouté, tout de suite c'est plus facile de persister la donnée, la synchroniser, et la passer à `renderPNG`.

**Comment by zhouzi** [comment]
Pour en avoir discuté avec @mootookoi le plus compliqué avec ce ticket c'est de savoir ce qu'on veut exactement en terme de design et l'impact que peut avoir l'ajustement de la taille du texte & co.

Quelques références qui peuvent inspirer :

1. Trouvé dans la newsletter de [Max](https://x.com/maxvohnout) : ![](https://github.com/zhouzi/broll/assets/2291025/d94ec85d-9122-4197-a014-1f48f1dbbdc9)
2. Généré par [wid.yt](https://wid.yt/youtube-widget) : ![](https://github.com/zhouzi/broll/assets/2291025/4c4247f0-9bae-40a3-9bc1-f0fa8381478f)
3. Envoyé en DM par un monteur : ![](https://github.com/zhouzi/broll/assets/2291025/c35d2eba-ed5e-4950-923f-5476c99b8336)

J'aime beaucoup la 1. qui fait une bonne utilisation de l'espace et correspond à l'usage cible (dans un coin de l'écran ou dans une colonne large). Y'a moyen d'y ajouter les autres informations.
