### ISSUE TITLE
Améliorer interface mobile

### ISSUE THREAD

**Issue by mootookoi** [zhouzi/broll#32]
Sur mobile, quand on clique sur un select, ça trigger la palette de couleur en dessous de temps en temps.
Puis sur Chrome, quand on clique sur le select, ça change les dimensions de l'interface.

**Comment by zhouzi** [comment]
> quand on clique sur un select, ça trigger la palette de couleur en dessous de temps en temps

Trop bizarre ça, bien vu 🙏

> sur Chrome, quand on clique sur le select, ça change les dimensions de l'interface

À vérifier mais je pense que c'est dû à la taille de la police. Si elle est "trop petite" (à voir ce que ça veut dire pour chaque navigateur) et que tu cliques dans un champ, le navigateur zoom.

Je fusionne ce ticket avec #26 pour centraliser ces retours, merci encore 🙏
