### ISSUE TITLE
Optimiser le chargement de la page

### ISSUE THREAD

**Issue by zhouzi** [zhouzi/broll#38]
J'ai le sentiment que le chargement initial est particulièrement lent, depuis que j'ai quitté Vercel pour mon VPS. Ce n'est peut-être qu'une impression mais il faudrait prendre quelques mesures et voir si il n'y a pas de quick wins.

**Comment by mootookoi** [comment]
J'ai testé ton app en prod. Je trouve qu'elle se charge vite ( depuis la France en tout cas ).
Par contre, un truc que je trouve plus embêtant c'est le temps de chargement des données de l'URL ou du localStorage. 
On a un gros lag entre les données par défaut et les données du user.

**Comment by zhouzi** [comment]
Merci, ça me rassure, surtout que j'ai une connexion internet très variable en ce moment.

> Par contre, un truc que je trouve plus embêtant c'est le temps de chargement des données de l'URL ou du localStorage.
> On a un gros lag entre les données par défaut et les données du user.

Ouais c'est chiant, ça cause un flicker 😔

Je ne sais pas trop comment le corriger parce que les données sont stockés côté client et qu'il faut donc nécessairement attendre le chargement de la page.

Une rustine pourrait être d'afficher une sorte d'écran de chargement ou de skeleton le temps qu'on initialise les valeurs proprement. Mais je sais pas trop.

@mootookoi tu en penses quoi ?

**EDIT**: y'a un monde où on pourrait arrêter de stocker dans le local storage aussi, le proposer avec une inscription pour le stocker en base de donnée (et donc faire du SSR pour éviter le flicker). Ça peut se justifier, surtout que l'inconvénient du local storage c'est que ça provoque une requête à l'API YouTube dès que tu charges la page (si la dernière vidéo est différente de celle par défaut). Autrement dit les utilisateurs non inscrits peuvent grignoter le quota malgré eux. Ne le faire que pour les utilisateurs inscrits permettrait de réduire le nombre de ces appels. En alternative pour ceux qui ne veulent vraiment pas s'inscrire on peut proposer de mettre en favoris l'URL avec leurs paramètres (mais bon, ils auraient aussi vite fait d'utiliser un autre outil, si celui-ci n'arrive pas à se différencier suffisamment pour qu'ils ne veulent pas s'inscrire).

**Comment by mootookoi** [comment]
Un skeleton est une bonne idée dans un premier temps. Puis ça servira toujours pour les non inscrits.
Pour les inscrits, comme tu l'a dis, ça sera facile à gérer côté serveur.
Après, à terme, il faudra virer la vidéo par défaut de la page d'accueil et la migrer vers une page de démo je pense.
Qu'en penses-tu @zhouzi ?

**Comment by zhouzi** [comment]
> Un skeleton est une bonne idée dans un premier temps. Puis ça servira toujours pour les non inscrits.

Oui tu as raison, ça serait même un meilleur indicateur de chargement dans tous les cas quand l'utilisateur change l'URL de la vidéo YouTube, j'ai créé #44 👍

> Après, à terme, il faudra virer la vidéo par défaut de la page d'accueil et la migrer vers une page de démo je pense.

Oui, idéalement il faudrait une landing page pour présenter l'app et une autre page pour la version gratuite. Je ne crée pas de ticket tout de suite à ce sujet parce que c'est encore très flou.

Je clos ce ticket, il n'y a pas de problème majeur à priori et les problèmes identifiés ont été découpé dans d'autres tickets.
